<?php
/**
 * Customer login form template
 *
 * @var $this Mage_Customer_Block_Form_Login
 */
?>

<div class="customer-account">

    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>

    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra')?>

    <div class="row">

        <div class="col-md-4 col-md-offset-2">
            <div class="account-panel">
                <a href="#" class="panel-link <?php if (!$this->helper('weltpixel_layerednavigation')->isMobileOrTablet()){?> active <?php }?>"><?php echo $this->__('I Have An Account'); ?></a>
                <div class="panel-details <?php if (!$this->helper('weltpixel_layerednavigation')->isMobileOrTablet()){?> active <?php }?>">
                    <form action="<?php echo $this->getPostActionUrl(); ?>" method="post" id="login-form">
                        <?php echo $this->getBlockHtml('formkey'); ?>
                        <h4><?php echo $this->__('Log Into Your Account'); ?></h4>
                        <ul class="form-list">
                            <li>
                                <div class="input-box">
                                    <input type="text" name="login[username]" id="email" value="<?php echo $this->escapeHtml($this->getUsername()); ?>" placeholder="<?php echo strtoupper($this->__('Email Address')); ?>" title="<?php echo $this->__('Email Address'); ?>" class="input-text required-entry validate-email" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="password" name="login[password]" placeholder="<?php echo strtoupper($this->__('Password')); ?>" id="pass" title="<?php echo $this->__('Password'); ?>" class="input-text required-entry validate-password" />
                                </div>
                            </li>
                            <li class="utils">
                                <a href="<?php echo $this->getForgotPasswordUrl(); ?>" class="forgot-password"><?php echo $this->__('Forgot Password'); ?></a>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                        </ul>
                        <div class="buttons-set">
                            <button type="submit" class="button" title="<?php echo $this->__('Continue'); ?>"><span><?php echo $this->__('Continue'); ?></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
        <div class="col-md-4">
            <div class="account-panel">
                <a href="#" class="panel-link"><?php echo $this->__('Create An Account'); ?></a>
                <div class="panel-details">
                    <h4><?php echo $this->__('Create New Account'); ?></h4>
                    <form action="<?php echo $this->helper('customer')->getRegisterPostUrl()?>" method="post" id="form-validate" enctype="multipart/form-data">
                        <ul class="form-list">
                            <li>
                                <div class="input-box">
                                    <input type="text" name="firstname" id="firstname" value="" placeholder="<?php echo strtoupper($this->__('First Name')); ?>" title="<?php echo $this->__('First Name'); ?>" class="input-text required-entry" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="text" name="lastname" id="lastname" value="" placeholder="<?php echo strtoupper($this->__('Last Name')); ?>" title="<?php echo $this->__('Last Name'); ?>" class="input-text required-entry" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="text" name="email" id="email_address" value="" placeholder="<?php echo strtoupper($this->__('Email Address')); ?>" title="<?php echo $this->__('Email Address'); ?>" class="input-text validate-email required-entry" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="password" name="password" id="password" placeholder="<?php echo strtoupper($this->__('Password')); ?>" title="<?php echo $this->__('Password'); ?>" class="input-text required-entry validate-password" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="password" name="confirmation" id="confirmation" placeholder="<?php echo strtoupper($this->__('Confirm Password')); ?>" title="<?php echo $this->__('Confirm Password'); ?>" class="input-text required-entry validate-cpassword" />
                                </div>
                            </li>
                            <li class="utils">
                                <div class="clear" style="height: 14px;"></div>
                                <input type="checkbox" name="is_subscribed" id="is_subscribed" value="1" title="<?php echo $this->__('Sign Up for Newsletter'); ?>" class="checkbox" />
                                <label for="is_subscribed"><?php echo $this->__('Receive Emails'); ?></label>
                                <div class="clear"></div>
                            </li>
                        </ul>
                        <div class="buttons-set">
                            <button type="submit" class="button" title="<?php echo $this->__('Continue'); ?>"><span><?php echo $this->__('Continue'); ?></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>

    <script>
    //<![CDATA[
        jQuery(document).ready(function($) {

            $('.panel-link').on('click', function() {
                $('.customer-account .panel-link').show();
                $('.customer-account .panel-details').hide();
                $(this).hide();
                $(this).next().show();
                return false;
            })

        });
    //]]>
    </script>

    <script>
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        Form.getElements('form-validate').each(function(element) {
            element.setAttribute('autocomplete', 'off');
        });
    //]]>
    </script>    

</div>