<?php
$_helper = Mage::helper('weltpixel_selector');
?>

<script type="text/javascript">

    window.onload = loadScript;

    function loadScript() {
        var script = document.createElement("script");
        script.type = "text/javascript";
        var source  = "http://maps.googleapis.com/maps/api/js?v=3.17&sensor=false&callback=init";
<?php
$apiKey = $_helper->getGoogleApiKey();
if (strlen($apiKey)):
    ?>
                    source += '&key=<?php echo $apiKey ?>';
<?php endif; ?>
                script.src = source;
                document.body.appendChild(script);
            }


            function init() {
<?php if ($_helper->getContactLatitude() && $_helper->getContactLatitude()): ?>
                    var myLatlng = new google.maps.LatLng(<?php echo $_helper->getContactLatitude() ?>, <?php echo $_helper->getContactLongitude() ?>) ;
<?php else: ?>
                    var myLatlng = new google.maps.LatLng(30.3118257, 78.0375107) ; //some default
<?php endif; ?>
                var mapOptions = {
                    zoom: 11,
                    center: myLatlng,
                    styles: [	{		featureType:'water',		stylers:[{color:'#46bcec'},{visibility:'on'}]	},{		featureType:'landscape',		stylers:[{color:'#f2f2f2'}]	},{		featureType:'road',		stylers:[{saturation:-100},{lightness:45}]	},{		featureType:'road.highway',		stylers:[{visibility:'simplified'}]	},{		featureType:'road.arterial',		elementType:'labels.icon',		stylers:[{visibility:'off'}]	},{		featureType:'administrative',		elementType:'labels.text.fill',		stylers:[{color:'#444444'}]	},{		featureType:'transit',		stylers:[{visibility:'off'}]	},{		featureType:'poi',		stylers:[{visibility:'off'}]	}]
                };

                var mapElement = document.getElementById('map');
                var map = new google.maps.Map(mapElement, mapOptions);

                 marker = new google.maps.Marker({
                    map:map,
                    draggable: false,
                    animation: google.maps.Animation.DROP,
                    position: myLatlng
                  });
            }
</script>


<div id="map"></div>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="w">
    <div class="col-sm-6 col-xs-12 topmargin">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_contact_page')->toHtml() ?>
    </div>
    <div class="col-sm-6 col-xs-12 form-area">
        <div class="page-title">
            <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
        </div>
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
            <div class="fieldset">
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <div class="input-box">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                        </div>
                    </li>
                    <li class="wide">
                        <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text notes" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
