<?php
/**
 * @see Mage_CatalogInventory_Block_Stockqty_Composite
 */

$_stockQty = $this->getStockQty();
$_isMsgVisible = $this->isMsgVisible();
$_placeholderId = $this->getPlaceholderId();
$_detailsPlaceholderId = $this->getDetailsPlaceholderId();
?>

<?php if ($_isMsgVisible): ?>
    <div class="availability-only" id="<?php echo $_placeholderId; ?>"><i class="icon-line-clock"></i><span><?php echo $this->__('Only %s left', $_stockQty); ?></span></div>
    <table id="<?php echo $_detailsPlaceholderId; ?>" class="availability-only-details no-display">
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name'); ?></th>
                <th class="a-center"><?php echo $this->__('Qty'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getChildProducts() as $childProduct) : ?>
            <?php $childProductStockQty = $this->getProductStockQty($childProduct); ?>
            <?php if ($childProductStockQty > 0): ?>
                <tr>
                    <td><?php echo $childProduct->getName(); ?></td>
                    <td class="a-center"><?php echo $childProductStockQty; ?></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script>
    //<![CDATA[
    $('<?php echo $_placeholderId; ?>').observe('click', function(event) {
        this.toggleClassName('expanded');
        $('<?php echo $_detailsPlaceholderId; ?>').toggleClassName('no-display');
        event.stop();
        decorateTable('<?php echo $_detailsPlaceholderId; ?>');
    });
    //]]>
    </script>
<?php endif; ?>
