<h4><span><?php echo $this->__('Write Your Own Review'); ?></span></h4>
<?php if ($this->getAllowWriteReviewFlag()): ?>
    <p><?php echo $this->__('You\'re reviewing:'); ?> <strong class="uppercase"><?php echo $this->escapeHtml($this->getProductInfo()->getName()); ?></strong></p>
    <form action="<?php echo $this->getAction(); ?>" method="post" id="review-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before'); ?>
            <ul class="form-list row">
                <li class="col-xs-12">
                    <?php if ($this->getRatings() && $this->getRatings()->getSize()): ?>
                        <label class="required" style="margin-bottom: 20px;"><em>*</em><?php echo $this->__('How do you rate this product?'); ?></label>
                        <div class="input-box">
                            <span id="input-message-box"></span>
                            <table class="ratings-table" id="product-review-table">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <?php for ($i = 1; $i <= 5; $i++): ?>
                                        <th class="star">
                                            <div class="rating-box">
                                                <div class="rating" style="width: <?php echo 20*$i; ?>%;"></div>
                                            </div>
                                        </th>
                                        <?php endfor; ?>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->getRatings() as $_rating): ?>
                                    <tr>
                                        <th><?php echo $this->escapeHtml($_rating->getRatingCode()); ?></th>
                                        <?php foreach ($_rating->getOptions() as $_option): ?>
                                        <td class="value"><input type="radio" name="ratings[<?php echo $_rating->getId(); ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()); ?>_<?php echo $_option->getValue(); ?>" value="<?php echo $_option->getId(); ?>" class="radio" /></td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    <?php endif; ?>
                </li>
                <li class="col-xs-12">
                    <div class="input-box">
                        <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" placeholder="<?php echo $this->__('Nickname'); ?>" value="<?php echo $this->escapeHtml($data->getNickname()); ?>" />
                    </div>
                </li>
                <li class="col-xs-12">
                    <div class="input-box">
                        <input type="text" name="title" id="summary_field" class="input-text required-entry" placeholder="<?php echo $this->__('Summary of Your Review'); ?>" value="<?php echo $this->escapeHtml($data->getTitle()); ?>" />
                    </div>
                </li>
                <li class="col-xs-12">
                    <div class="input-box">
                        <textarea name="detail" id="review_field" cols="5" rows="3" placeholder="<?php echo $this->__('Review'); ?>" class="input-text required-entry"><?php echo $this->escapeHtml($data->getDetail()); ?></textarea>
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set">
            <button type="submit" title="<?php echo $this->__('Submit Review'); ?>" class="button"><span><?php echo $this->__('Submit Review'); ?></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above'); ?>', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
<?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()); ?>
    </p>
<?php endif; ?>