<?php
$_cartQty = $this->getSummaryCount();
if ( is_null($_cartQty) )  {
    $_cartQty = 0;
}
$_cartUrl = $this->getUrl('checkout/cart');
$_checkoutUrl = $this->getCheckoutUrl();
$_items = $this->getRecentItems();
$_itemsCount = count($_items);
?>

<?php
if ($_itemsCount == 0)
{
    ?>
    <a href="<?php echo $_cartUrl; ?>" class="summary qa-link"><i class="icon icon-shopping-cart"></i> <span><?php echo $this->__('%s', 0); ?></span></a>
    <div class="details">
        <p><?php echo $this->__('You have no items in your shopping cart.'); ?></p>
    </div>
    <?php
}
else
{
    ?>
    <a href="<?php echo $_cartUrl; ?>" class="summary qa-link"><i class="icon icon-shopping-cart"></i> <span><?php echo $this->__($_cartQty); ?></span></a>
    <div class="details">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_shopping_cart_top')->toHtml() ?><br>
        <span class="mini-cart-title"><?php echo $this->__('Recently added item(s)'); ?></span>
        <ol class="mini-products-list">
            <?php foreach ($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item); ?>
            <?php endforeach; ?>
        </ol>
        <div class="subtotal-wrapper">
            <div class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()); ?>
                <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                    <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true); ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <div class="buttons clearfix">
            <a class="mini-cart-view-cart simple-button" href="<?php echo $_cartUrl; ?>" title="<?php echo $this->__('View Cart'); ?>"><?php echo $this->__('View Cart'); ?></a>
            <a class="mini-cart-checkout button" href="<?php echo $_checkoutUrl; ?>" title="<?php echo $this->__('Checkout'); ?>"><?php echo $this->__('Checkout'); ?></a>
        </div>
    </div>
    <?php
}
?>
