<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Additional WeltPixel Cache Management') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getRefreshCssUrl();?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Refresh Template Settings') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated css file.')?>
        </td>
    </tr>
</table>
