<div class="importexport_content_container" id="import_export_page_container" style="display: none">
    <div class="content-header"><h3>WeltPixel Page Import/Export</h1></div>
    <div class="content">
        <table cellspacing="10" cellpadding="10" class="form-edit">
            <tbody>
                <tr>
                    <td width="50%" >
                        <div class="entry-edit" >
                            <div>
                                <div class="entry-edit-head">
                                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Export Pages') ?></h4>
                                </div>
                                <div class="fieldset ">
                                    <div class="hor-scroll hor-scroll-simple">
                                        <form  name="export_page" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/wpsetup/exportentity"); ?>" method="post" >
                                            <?php echo $this->getBlockHtml('formkey') ?>
                                            <input type="hidden" name="export_entity" value="page" />
                                            <table cellspacing="10" cellpadding="10" >
                                                <tr>
                                                    <td ><?php echo $this->__('Select Store') ?>: </td>
                                                    <td>
                                                        <?php
                                                        $options = array('id' => 'export_store', 'name' => 'export_store', 'size' => '13', 'style' => 'width: 280px');
                                                        echo Mage::helper('weltpixel_setup')->getStoreOptions($options);
                                                        ?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2"> <input type="submit"  class="form-button" value="<?php echo $this->__('Export') ?>"/></td>
                                                </tr>
                                            </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td width="50%">
                        <div class="entry-edit">
                            <div>
                                <div class="entry-edit-head">
                                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Import Pages') ?></h4>
                                </div>
                                <div class="fieldset ">
                                    <div class="hor-scroll hor-scroll-simple">
                                        <form name="import_page"  action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/wpsetup/importentity"); ?>" method="post"  enctype="multipart/form-data">
                                            <?php echo $this->getBlockHtml('formkey') ?>
                                            <input type="hidden" name="import_entity" value="page" />
                                            <table cellspacing="10" cellpadding="10" >
                                                <tr>
                                                    <td ><?php echo $this->__('Select Store') ?>: </td>
                                                    <td>
                                                        <?php
                                                        $options = array('id' => 'import_store', 'name' => 'import_store[]', 'size' => '13', 'style' => 'width: 280px', 'multiple' => true);
                                                        echo Mage::helper('weltpixel_setup')->getStoreOptions($options, true);
                                                        ?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td ><?php echo $this->__('Overwrite') ?>: </td>
                                                    <td>
                                                        <select name="import_forced">
                                                            <option value="0" ><?php echo $this->__('No') ?></option>
                                                            <option value="1" ><?php echo $this->__('Yes') ?></option>
                                                        </select>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo $this->__('Select a file') ?>: </td>
                                                    <td><input type="file" name="import_file" /> </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2"> <input type="submit"  class="form-button add" value="<?php echo $this->__('Import') ?>"/></td>
                                                </tr>
                                            </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="entry-edit" >
                            <div>
                                <div class="entry-edit-head">
                                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Export From / Import To Pages') ?></h4>
                                </div>
                                <div class="fieldset " >
                                    <div class="hor-scroll ">
                                        <form name="export_import_page"  action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/wpsetup/exportimport"); ?>" method="post" >
                                            <?php echo $this->getBlockHtml('formkey') ?>
                                            <input type="hidden" name="exportimport_entity" value="page" />
                                            <table cellspacing="10" cellpadding="10" >
                                                <tr>
                                                    <td>
                                                        <table cellspacing="10" cellpadding="10" >
                                                            <tr>
                                                                <td ><?php echo $this->__('Select Store to Export From') ?>: </td>
                                                                <td>
                                                                    <?php
                                                                    $options = array('id' => 'exportimport_store_from', 'name' => 'exportimport_store_from', 'size' => '13', 'style' => 'width: 280px');
                                                                    echo Mage::helper('weltpixel_setup')->getStoreOptions($options);
                                                                    ?>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                    <td>
                                                        <table cellspacing="10" cellpadding="10" >
                                                            <tr>
                                                                <td ><?php echo $this->__('Select Store to import To') ?>: </td>
                                                               <td>
                                                                    <?php
                                                                    $options = array('id' => 'exportimport_store_to', 'name' => 'exportimport_store_to', 'size' => '13', 'style' => 'width: 280px');
                                                                    echo Mage::helper('weltpixel_setup')->getStoreOptions($options);
                                                                    ?>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td ><?php echo $this->__('Overwrite') ?>: </td>
                                                                <td>
                                                                    <select name="exportimport_forced">
                                                                        <option value="0" ><?php echo $this->__('No') ?></option>
                                                                        <option value="1" ><?php echo $this->__('Yes') ?></option>
                                                                    </select>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2"> <input type="submit"  class="form-button" value="<?php echo $this->__('Export/Import') ?>"/></td>
                                                </tr>
                                            </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
</div>