<?php
/**
 * Product list toolbar
 */
?>

<?php if ($this->getCollection()->getSize()): ?>
    <div class="toolbar <?php echo Mage::registry('tbp'); ?>">
        <?php if ($this->isExpanded()): ?>
        <div class="sorter">
            <?php if ($this->isEnabledViewSwitcher()): ?>
            <div class="view-mode">
                <?php $_modes = $this->getModes(); ?>
                <?php if ($_modes && count($_modes) > 1): ?>
                    <label><?php echo $this->__('View as'); ?>:</label>
                    <?php foreach ($this->getModes() as $_code => $_label): ?>
                        <?php if ($this->isModeActive($_code)): ?>
                            <span title="<?php echo $_label; ?>" class="<?php echo strtolower($_code); ?>"><i class="icon-grid"></i><em><?php echo $_label; ?></em></span>
                        <?php else: ?>
                            <a href="<?php echo $this->getModeUrl($_code); ?>" title="<?php echo $_label; ?>" class="<?php echo strtolower($_code); ?>"><i class="icon-line2-list"></i><em><?php echo $_label; ?></em></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="sort-by">
                <label><?php echo $this->__('Sort By'); ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                        <option value="<?php echo $this->getOrderUrl($_key, 'asc'); ?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>><?php echo $this->__($_order); ?></option>
                    <?php endforeach; ?>
                </select>
                <?php if ($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc'); ?>" title="<?php echo $this->__('Set Ascending Direction'); ?>"><i class="icon-chevron-up"></i></a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc'); ?>" title="<?php echo $this->__('Set Descending Direction'); ?>"><i class="icon-chevron-down"></i></a>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <?php echo $this->getPagerHtml(); ?>
    </div>
<?php endif; ?>