<?php
$_productCollection = $this->getItemCollection()->getItems();
$this->resetItemsIterator();
$_useRetina         = Mage::getStoreConfig('weltpixel_selector/customization_settings/retina');
$_imgSize = 270;
?>

<?php if (count($_productCollection)): ?>
<div class="heading-block center">
    <h3><?php echo $this->__("BASED ON YOUR SELECTION, YOU MAY BE INTERESTED IN THE FOLLOWING ITEMS:"); ?></h3>
</div>
    <div id="upsell-products" class="products-grid ">
        <?php
            // limit the number of upsale items using the admin setting if the limit is > 0
            $upsaleLimit = (int)Mage::getStoreConfig('weltpixel_selector/productpageoptions/upsaleproductsnumber');
            if($upsaleLimit > 0) {
                $_productCollection = array_slice($_productCollection,0,$upsaleLimit);
            }
        ?>
        <?php foreach ($_productCollection as $_product): ?>
            <div class="item">
                <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                    <img
                        src = "<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                        data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                        <?php if($_useRetina) : ?>
                            data-src-retina = "<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(2*$_imgSize); ?>"
                        <?php endif; ?>
                        alt="<?php echo $this->escapeHtml($_product->getName()); ?>"
                /></a>
                <h4><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>"><?php echo $this->escapeHtml($_product->getName()); ?></a></h4>
                <?php echo $this->getPriceHtml($_product, true, '-upsell'); ?>
            </div>
        <?php endforeach; ?>
    </div>   
    <script>
    // <![CDATA[
        jQuery(document).ready(function($) {
            var owl = $("#upsell-products");
            owl.owlCarousel({
                items: 5,
                pagination: false,
                rewindNav: false,
                lazyLoad : true,
                navigation: true,
                navigationText: [
                    '<i class="icon-angle-left"></i>',
                    '<i class="icon-angle-right"></i>'
                ]
            });
        });
    // ]]>
    </script>
<?php endif; ?>