<footer id="page-footer">
    <div id="page-footer-section-01">
        <div class="w">
            <div class="footer-section1-content row">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section1-1')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section1-2')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section1-3')->toHtml() ?>
            </div>
        </div>
    </div>
    <div id="page-footer-section-02">
        <div class="w">
            <div class="footer-section2-content row">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section2-1')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section2-2')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section2-3')->toHtml() ?>
            </div>
        </div>
    </div>
    <div id="page-footer-section-03">
        <div class="w">
			<div class="footer-section3-content row">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section3-1')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section3-2')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('weltpixel_footer_section3-3')->toHtml() ?>
	        </div>
        </div>
    </div>
</footer>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'weltpixel/features/functions.js' ?> "></script>